### ISSUE TITLE
获取真实房间号的更兼容接口

### ISSUE THREAD

**Issue by reitowo** [Luncode/bilibili_live_wssdemo#1]
https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids[]={roomId}

**Comment by Luncode** [comment]
> [https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids[]={roomId}](https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids%5B%5D=%7BroomId%7D)

好的 测试了一下可以用 后面有时间我加上
